textos = {
    "pt": {
        "menu_opcoes": "\n=== Menu de Opções ===",
        "investir": "[1] Investir",
        "cambio": "[2] Câmbio",
        "registrar_despesas": "[3] Registrar Despesas",
        "transferir": "[4] Transferir entre Usuários",
        "sair": "[5] Sair",
        "escolha": "\nEscolha uma opção: ",
        "transferencia": "\n=== Transferência entre Usuários ===",
        "saldo_insuficiente": "Saldo insuficiente! Tente novamente com um valor menor.",
        "valor_invalido": "Valor inválido!",
        "saindo": "\nSaindo do sistema. Até logo!",
        "opcao_invalida": "\nOpção inválida. Tente novamente."
    },
    "en": {
        "menu_opcoes": "\n=== Options Menu ===",
        "investir": "[1] Invest",
        "cambio": "[2] Currency Exchange",
        "registrar_despesas": "[3] Register Expenses",
        "transferir": "[4] Transfer Between Users",
        "sair": "[5] Exit",
        "escolha": "\nChoose an option: ",
        "transferencia": "\n=== Transfer Between Users ===",
        "saldo_insuficiente": "Insufficient balance! Please try again with a smaller amount.",
        "valor_invalido": "Invalid amount!",
        "saindo": "\nExiting the system. Goodbye!",
        "opcao_invalida": "\nInvalid option. Please try again."
    },
    "es": {
        "menu_opcoes": "\n=== Menú de Opciones ===",
        "investir": "[1] Invertir",
        "cambio": "[2] Cambio",
        "registrar_despesas": "[3] Registrar Gastos",
        "transferir": "[4] Transferir entre Usuarios",
        "sair": "[5] Salir",
        "escolha": "\nElija una opción: ",
        "transferencia": "\n=== Transferencia entre Usuarios ===",
        "saldo_insuficiente": "¡Saldo insuficiente! Intente de nuevo con una cantidad menor.",
        "valor_invalido": "¡Valor inválido!",
        "saindo": "\nSaliendo del sistema. ¡Hasta luego!",
        "opcao_invalida": "\nOpción inválida. Intente de nuevo."
    },
    "fr": {
        "menu_opcoes": "\n=== Menu des Options ===",
        "investir": "[1] Investir",
        "cambio": "[2] Échange de Devises",
        "registrar_despesas": "[3] Enregistrer des Dépenses",
        "transferir": "[4] Transférer entre Utilisateurs",
        "sair": "[5] Quitter",
        "escolha": "\nChoisissez une option : ",
        "transferencia": "\n=== Transfert entre Utilisateurs ===",
        "saldo_insuficiente": "Solde insuffisant ! Veuillez réessayer avec un montant plus petit.",
        "valor_invalido": "Montant invalide !",
        "saindo": "\nFermeture du système. À bientôt !",
        "opcao_invalida": "\nOption invalide. Veuillez réessayer."
    },
    "de": {
        "menu_opcoes": "\n=== Optionsmenü ===",
        "investir": "[1] Investieren",
        "cambio": "[2] Währungsumtausch",
        "registrar_despesas": "[3] Ausgaben erfassen",
        "transferir": "[4] Zwischen Benutzern überweisen",
        "sair": "[5] Beenden",
        "escolha": "\nWählen Sie eine Option: ",
        "transferencia": "\n=== Überweisung zwischen Benutzern ===",
        "saldo_insuficiente": "Unzureichendes Guthaben! Bitte versuchen Sie es mit einem kleineren Betrag.",
        "valor_invalido": "Ungültiger Betrag!",
        "saindo": "\nSystem wird beendet. Auf Wiedersehen!",
        "opcao_invalida": "\nUngültige Option. Bitte versuchen Sie es erneut."
    },
    "ru": {
        "menu_opcoes": "\n=== Меню опций ===",
        "investir": "[1] Инвестировать",
        "cambio": "[2] Обмен валюты",
        "registrar_despesas": "[3] Зарегистрировать расходы",
        "transferir": "[4] Перевод между пользователями",
        "sair": "[5] Выйти",
        "escolha": "\nВыберите опцию: ",
        "transferencia": "\n=== Перевод между пользователями ===",
        "saldo_insuficiente": "Недостаточно средств! Попробуйте еще раз с меньшей суммой.",
        "valor_invalido": "Неверное значение!",
        "saindo": "\nВыход из системы. До свидания!",
        "opcao_invalida": "\nНеверная опция. Попробуйте еще раз."
    },
    "jp": {
        "menu_opcoes": "\n=== オプションメニュー ===",
        "investir": "[1] 投資",
        "cambio": "[2] 両替",
        "registrar_despesas": "[3] 支出を記録する",
        "transferir": "[4] ユーザー間で送金する",
        "sair": "[5] 終了する",
        "escolha": "\nオプションを選択してください: ",
        "transferencia": "\n=== ユーザー間の送金 ===",
        "saldo_insuficiente": "残高不足です！少ない金額で再試行してください。",
        "valor_invalido": "無効な金額です！",
        "saindo": "\nシステムを終了します。さようなら！",
        "opcao_invalida": "\n無効なオプションです。再試行してください。"
    },
    "ko": {
        "menu_opcoes": "\n=== 옵션 메뉴 ===",
        "investir": "[1] 투자",
        "cambio": "[2] 환전",
        "registrar_despesas": "[3] 지출 등록",
        "transferir": "[4] 사용자 간 이체",
        "sair": "[5] 종료",
        "escolha": "\n옵션을 선택하세요: ",
        "transferencia": "\n=== 사용자 간 이체 ===",
        "saldo_insuficiente": "잔액이 부족합니다! 더 적은 금액으로 다시 시도하세요.",
        "valor_invalido": "잘못된 금액입니다!",
        "saindo": "\n시스템을 종료합니다. 안녕히 가세요!",
        "opcao_invalida": "\n잘못된 옵션입니다. 다시 시도하세요."
    }
}